### ISSUE TITLE
Include forked point from pepe2k/u-boot_mod

### ISSUE THREAD

**Issue by thornley-touchstar** [domino-team/uboot-domino#1]
Just curious if you can confirm the point you forked from pepe2k/u-boot-mod.

See: - https://github.com/pepe2k/u-boot_mod

I suspect it was commit - a404a56e48c2796e4621b42cd461bf5e95ea5e09 [a404a56]

**Comment by alzhao** [comment]
Sorry this information is lost and I don't know how to find it back.
